/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AABDD_Project;

import javax.swing.JOptionPane;

/**
 *
 * @author mahdj
 */
public class Action_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Product_Panel
     */
    public Action_Panel() {
        initComponents();
    }
    public void delete(boolean delete){
        if (table.equalsIgnoreCase("produit")){
           Sql.DeleteFromProduit(table);
        }else if (table.equalsIgnoreCase("affectation")){
            
        }else if (table.equalsIgnoreCase("command")){
            
        }else if (table.equalsIgnoreCase("department")){
            
        }else if (table.equalsIgnoreCase("employe")){
            
        }else if (table.equalsIgnoreCase("fournisseur")){
            
        }else if (table.equalsIgnoreCase("sortie")){
            
        }else if (table.equalsIgnoreCase("livraison")){
            
        }else if (table.equalsIgnoreCase("categorie")){
           
        }else {
            JOptionPane.showMessageDialog(null, "error dans le type de table");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        ADD = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Restore = new javax.swing.JButton();
        Deleted_Checkbox = new javax.swing.JCheckBox();
        Consultation_Container = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Restore.setText("Restore");
        Restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreActionPerformed(evt);
            }
        });

        Deleted_Checkbox.setText("Deleted");
        Deleted_Checkbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deleted_Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deleted_CheckboxActionPerformed(evt);
            }
        });

        Consultation_Container.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Restore, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Deleted_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(Consultation_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(Deleted_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Restore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Consultation_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        edit=true;
    }//GEN-LAST:event_UpdateActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        edit=false;
    }//GEN-LAST:event_ADDActionPerformed

    private void Deleted_CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deleted_CheckboxActionPerformed
        active=!Deleted_Checkbox.isSelected();
        MainFrame.consultation_Panel1.active=active;
        MainFrame.consultation_Panel1.fillTable();
        
    }//GEN-LAST:event_Deleted_CheckboxActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        table=MainFrame.consultation_Panel1.table;
        String ID=MainFrame.consultation_Panel1.Selected_ID();
        if (table.equalsIgnoreCase("produit")){
            System.out.println(ID);
           Sql.DeleteFromProduit(ID);
        }else if (table.equalsIgnoreCase("affectation")){
            
        }else if (table.equalsIgnoreCase("command")){
            
        }else if (table.equalsIgnoreCase("department")){
            Sql.DeleteFromDepartement(ID);
        }else if (table.equalsIgnoreCase("employe")){
            Sql.DeleteFromEmploye(ID);
        }else if (table.equalsIgnoreCase("fournisseur")){
            Sql.DeleteFromFournisseur(ID);
        }else if (table.equalsIgnoreCase("sortie")){
            
        }else if (table.equalsIgnoreCase("livraison")){
            
        }else if (table.equalsIgnoreCase("categorie")){
           
        }else {
            JOptionPane.showMessageDialog(null, "error dans le type de table");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void RestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreActionPerformed
        table=MainFrame.consultation_Panel1.table;
        String ID=MainFrame.consultation_Panel1.Selected_ID();
        if (table.equalsIgnoreCase("produit")){
            System.out.println(ID);
           Sql.RestoreFromProduit(ID);
        }else if (table.equalsIgnoreCase("affectation")){
            
        }else if (table.equalsIgnoreCase("command")){
            
        }else if (table.equalsIgnoreCase("department")){
            Sql.RestoreFromDepartement(ID);
        }else if (table.equalsIgnoreCase("employe")){
            Sql.RestoreFromEmploye(ID);
        }else if (table.equalsIgnoreCase("fournisseur")){
            Sql.RestoreFromFournisseur(ID);
        }else if (table.equalsIgnoreCase("sortie")){
            
        }else if (table.equalsIgnoreCase("livraison")){
            
        }else if (table.equalsIgnoreCase("categorie")){
           
        }else {
            JOptionPane.showMessageDialog(null, "error dans le type de table");
        }
    }//GEN-LAST:event_RestoreActionPerformed
    public static String table ="";
    public static boolean active=true,edit=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    public javax.swing.JPanel Consultation_Container;
    private javax.swing.JButton Delete;
    private javax.swing.JCheckBox Deleted_Checkbox;
    private javax.swing.JButton Restore;
    private javax.swing.JButton Update;
    public static javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
