/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AABDD_Project;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author mahdj
 */

public class Consultation_Panel extends javax.swing.JPanel {
    public String Selected_ID(){
        String id="";
        if (table.equalsIgnoreCase("produit")){
            id=Methode.get_Selected_ID(products_Table1.Product_table);
        }else if (table.equalsIgnoreCase("affectation")){
            id=Methode.get_Selected_ID(affectation_Table1.Affectation_Table);
        }else if (table.equalsIgnoreCase("command")){
            id=Methode.get_Selected_ID(command_Table1.Command_Table);
        }else if (table.equalsIgnoreCase("department")){
            id=Methode.get_Selected_ID(departments_Table1.Departments_Table);
        }else if (table.equalsIgnoreCase("employe")){
            id=Methode.get_Selected_ID(employee_Table1.Employee_Table);
        }else if (table.equalsIgnoreCase("fournisseur")){
            id=Methode.get_Selected_ID(fourniseur_Table1.fournisseur_Table);
        }else if (table.equalsIgnoreCase("sortie")){
            id=Methode.get_Selected_ID(sortie_Table1.Sortie_Table);
        }else if (table.equalsIgnoreCase("livraison")){
            id=Methode.get_Selected_ID(livraison_Table1.Laivraison_Table);
        }else if (table.equalsIgnoreCase("categorie")){
            id=Methode.get_Selected_ID(cat_Table1.categorie_Table);
        }
        return id;
    }   
    public void fillTable(){
        Sql.commit();
        if (table.equalsIgnoreCase("produit")){
            Table_Container.removeAll();
            Table_Container.add(products_Table1,BorderLayout.CENTER); 
            products_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("affectation")){
            Table_Container.removeAll();
            Table_Container.add(affectation_Table1,BorderLayout.CENTER); 
            affectation_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("command")){
            Table_Container.removeAll();
            Table_Container.add(command_Table1,BorderLayout.CENTER);
            command_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("department")){
            Table_Container.removeAll();
            Table_Container.add(departments_Table1,BorderLayout.CENTER); 
            departments_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("employe")){
            Table_Container.removeAll();
            Table_Container.add(employee_Table1,BorderLayout.CENTER); 
            employee_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("fournisseur")){
            Table_Container.removeAll();
            Table_Container.add(fourniseur_Table1,BorderLayout.CENTER); 
            fourniseur_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("sortie")){
            Table_Container.removeAll();
            Table_Container.add(sortie_Table1,BorderLayout.CENTER); 
            sortie_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("livraison")){
            Table_Container.removeAll();
            Table_Container.add(livraison_Table1,BorderLayout.CENTER); 
            livraison_Table1.fillTable(active);
        }else if (table.equalsIgnoreCase("categorie")){
            Table_Container.removeAll();
            Table_Container.add(cat_Table1,BorderLayout.CENTER); 
            cat_Table1.fillTable(active);
        }else {
            JOptionPane.showMessageDialog(null, "error dans le type de table");
        }
        refresh();
        
    }
    public void refresh(){
        Table_Container.repaint();
        Table_Container.revalidate();
    }
    /**
     * Creates new form Categories_Panel
     */
    public Consultation_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departments_Table1 = new AABDD_Project.Departments_Table();
        employee_Table1 = new AABDD_Project.Employee_Table();
        fourniseur_Table1 = new AABDD_Project.Fournisseur_Table();
        products_Table1 = new AABDD_Project.Products_Table();
        affectation_Table1 = new AABDD_Project.Affectation_Table();
        command_Table1 = new AABDD_Project.Command_Table();
        sortie_Table1 = new AABDD_Project.Sortie_Table();
        livraison_Table1 = new AABDD_Project.Livraison_Table();
        cat_Table1 = new AABDD_Project.Cat_Table();
        Searchfield = new javax.swing.JTextField();
        Table_Container = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 242));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 159, 205), 1, true));

        Searchfield.setBackground(new java.awt.Color(232, 232, 232));
        Searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchfieldKeyReleased(evt);
            }
        });

        Table_Container.setBackground(new java.awt.Color(244, 244, 242));
        Table_Container.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Searchfield, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Table_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchfieldKeyReleased
        
        if (table.equalsIgnoreCase("produit")){
            Methode.SearchInTheTable(products_Table1.Product_table, Searchfield);
        }else if (table.equalsIgnoreCase("affectation")){
           Methode.SearchInTheTable(affectation_Table1.Affectation_Table, Searchfield);
        }else if (table.equalsIgnoreCase("command")){
            Methode.SearchInTheTable(command_Table1.Command_Table, Searchfield);
        }else if (table.equalsIgnoreCase("department")){
            Methode.SearchInTheTable(departments_Table1.Departments_Table, Searchfield);
        }else if (table.equalsIgnoreCase("employe")){
            Methode.SearchInTheTable(employee_Table1.Employee_Table, Searchfield);
        }else if (table.equalsIgnoreCase("fournisseur")){
            Methode.SearchInTheTable(fourniseur_Table1.fournisseur_Table, Searchfield);
        }else if (table.equalsIgnoreCase("sortie")){
            Methode.SearchInTheTable(sortie_Table1.Sortie_Table, Searchfield);
        }else if (table.equalsIgnoreCase("livraison")){
            Methode.SearchInTheTable(livraison_Table1.Laivraison_Table, Searchfield);
        }else if (table.equalsIgnoreCase("categorie")){
           Methode.SearchInTheTable(cat_Table1.categorie_Table, Searchfield);
        }else {
            JOptionPane.showMessageDialog(null, "error dans le type de table");
        }
        refresh();
    }//GEN-LAST:event_SearchfieldKeyReleased

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(232, 232, 232));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(187, 191, 202));
    }//GEN-LAST:event_jButton1MouseExited
    public static  String table="";
    public static boolean active=true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Searchfield;
    public static javax.swing.JPanel Table_Container;
    public static AABDD_Project.Affectation_Table affectation_Table1;
    public static AABDD_Project.Cat_Table cat_Table1;
    public static AABDD_Project.Command_Table command_Table1;
    public static AABDD_Project.Departments_Table departments_Table1;
    public static AABDD_Project.Employee_Table employee_Table1;
    public static AABDD_Project.Fournisseur_Table fourniseur_Table1;
    public static javax.swing.JButton jButton1;
    public static AABDD_Project.Livraison_Table livraison_Table1;
    public static AABDD_Project.Products_Table products_Table1;
    public static AABDD_Project.Sortie_Table sortie_Table1;
    // End of variables declaration//GEN-END:variables
}
