/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AABDD_Project;

import javax.swing.DefaultListModel;
import javax.swing.JTextField;

/**
 *
 * @author mahdj
 */
public class Departments_Form extends javax.swing.JPanel {

    /**
     * Creates new form Employee_form
     */
    public Departments_Form() {
        initComponents();
    }
    public void fillForm(String actif){
        if(MainFrame.action_Panel1.edit){
            id=MainFrame.consultation_Panel1.Selected_ID();
            DefaultListModel l = Sql.SelectDepartement(actif, id);
            IntutileTxt.setText(l.getElementAt(0).toString());
            Nom_ChefTxt.setText(l.getElementAt(1).toString());
            Prenom_ChefTxt.setText(l.getElementAt(2).toString());
            Submit_button.setText("Update");
        }else{
            clear();
        }
    }
    public void clear(){
        Action_Panel.edit=false;
        IntutileTxt.setText("");
            Nom_ChefTxt.setText("");
            Prenom_ChefTxt.setText("");
            Submit_button.setText("ADD");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntutileTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_ChefTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Prenom_ChefTxt = new javax.swing.JTextField();
        Clear_button = new javax.swing.JButton();
        Submit_button = new javax.swing.JButton();

        jLabel1.setText("Intutile");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Nom Chef");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Prenom chef");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Clear_button.setText("Clear");
        Clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_buttonActionPerformed(evt);
            }
        });

        Submit_button.setText("ADD");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IntutileTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nom_ChefTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Prenom_ChefTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Clear_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Submit_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IntutileTxt)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nom_ChefTxt)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Prenom_ChefTxt)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear_button)
                    .addComponent(Submit_button)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed
        String intu=IntutileTxt.getText(),
                nom=Nom_ChefTxt.getText(),
                pre=Prenom_ChefTxt.getText();
        if (MainFrame.action_Panel1.edit){
            Sql.UpdateDepartments(id, intu, nom, pre);
        }else{
            Sql.InsertToDepartement(intu, nom, pre);
        }
        Sql.commit();
    }//GEN-LAST:event_Submit_buttonActionPerformed

    private void Clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_buttonActionPerformed
        clear();
    }//GEN-LAST:event_Clear_buttonActionPerformed

    public String id="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Clear_button;
    public javax.swing.JTextField IntutileTxt;
    public javax.swing.JTextField Nom_ChefTxt;
    public javax.swing.JTextField Prenom_ChefTxt;
    public javax.swing.JButton Submit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
