/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AABDD_Project;

/**
 *
 * @author mahdj
 */
public class User3_Menu extends javax.swing.JPanel {

    /**
     * Creates new form User1_Menu
     */
    public User3_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLabel2 = new javax.swing.JLabel();
        Commands_button = new javax.swing.JButton();
        Employe_button = new javax.swing.JButton();
        Log_out_button2 = new javax.swing.JButton();

        UsernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameLabel2.setText("User 3");

        Commands_button.setText("Commands");

        Employe_button.setText("Employe");

        Log_out_button2.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Commands_button, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
            .addComponent(Employe_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Log_out_button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(UsernameLabel2)
                .addGap(18, 18, 18)
                .addComponent(Commands_button)
                .addGap(18, 18, 18)
                .addComponent(Employe_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(Log_out_button2))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Commands_button;
    private javax.swing.JButton Employe_button;
    private javax.swing.JButton Log_out_button2;
    private javax.swing.JLabel UsernameLabel2;
    // End of variables declaration//GEN-END:variables
}
